#!/usr/bin/env python3
"""
emit_paper_numbers.py
Derive the manuscript's campaign numbers from the ledger instead of typing them.

The run count for the external campaign appeared in the manuscript in nine places and the discard
total in two. When the campaign grew, all eleven went stale together: the paper said `$80$ runs`
and `roughly $420{,}000$ discarded` when the ledger held `108` and `4{,}377{,}904`. Being wrong by
a factor of ten in a section whose entire argument is that benchmarks misreport their own sample
counts is not a typo, it is the paper committing the error it documents.

Hand-editing eleven sites is what created the problem, so this does not do that. It writes LaTeX
macros, the manuscript uses the macros, and the number exists once. `--check` verifies the
committed file still agrees with the ledger without rewriting it, so a build can gate on it.

The quantities are computed by `check_paper_omb_numbers.measured`, imported rather than
reimplemented -- two copies of this arithmetic would drift, and the drift would be invisible
because both would look authoritative.

CLI:
    python scripts/emit_paper_numbers.py
    python scripts/emit_paper_numbers.py --check
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from check_paper_omb_numbers import load_cells, measured  # noqa: E402

DEFAULT_OUT = os.path.join("docs", "generated", "paper_numbers.tex")

HEADER = (
    "% Generated by scripts/emit_paper_numbers.py from the campaign ledger.\n"
    "% Do not edit by hand -- run the script and commit the result.\n"
    "% Every number below is recomputed from docs/results/external_campaigns_index.csv.\n"
)


def latex_thousands(n):
    """12345678 -> 12{,}345{,}678, the separator that survives LaTeX's math mode."""
    return "{,}".join(_chunks(str(int(n))))


def _chunks(s):
    """Digit groups of three, counted from the right."""
    head = len(s) % 3 or 3
    return [s[:head]] + [s[i:i + 3] for i in range(head, len(s), 3)]


def macros(m):
    """The (name, value) pairs the manuscript may reference.

    Names are deliberately verbose. A macro called `\\n` in a 3000-line manuscript is a trap, and
    a macro whose name does not say which campaign it counts is the same trap one level up.

    The Kafka/Redis split exists because the negative-sample story is scoped: the withdrawal
    rests on the Kafka-driver corpus staying at zero negatives, while the Redis-driver
    replication caught real ones. One unsplit total let a claim about one corpus be silently
    contradicted by the other.
    """
    out = [
        ("ombRuns", str(m["n_runs"])),
        ("ombDiscarded", latex_thousands(m["discarded_total"])),
        ("ombKept", latex_thousands(m["kept_total"])),
        ("ombNegatives", latex_thousands(m["negatives"])),
        ("ombKafkaDiscarded", latex_thousands(m["kafka_discarded"])),
        ("ombKafkaNegatives", latex_thousands(m["kafka_negatives"])),
        ("ombRedisDiscarded", latex_thousands(m["redis_discarded"])),
        ("ombRedisNegatives", latex_thousands(m["redis_negatives"])),
    ]
    if m["retention_min"] is not None:
        out.append(("ombRetentionMin", "%.2f" % m["retention_min"]))
    if m["retention_max"] is not None:
        out.append(("ombRetentionMax", "%.2f" % m["retention_max"]))
    return out


def render(m):
    body = "".join("\\newcommand{\\%s}{%s}\n" % (name, val) for name, val in macros(m))
    return HEADER + body


def main(argv=None):
    ap = argparse.ArgumentParser(description="Emit campaign numbers as LaTeX macros")
    ap.add_argument("--ledger", default=os.path.join("docs", "results",
                                                     "external_campaigns_index.csv"))
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file disagrees with the ledger; write nothing")
    args = ap.parse_args(argv)

    if not os.path.exists(args.ledger):
        print("missing: %s" % args.ledger)
        return 1
    cells = load_cells(args.ledger)
    if not cells:
        print("no admissible cells in %s -- refusing to emit numbers from nothing" % args.ledger)
        return 1

    want = render(measured(cells))

    if args.check:
        if not os.path.exists(args.out):
            print("missing: %s (run without --check to create it)" % args.out)
            return 1
        with open(args.out, encoding="utf-8") as fh:
            have = fh.read()
        if have.replace("\r\n", "\n") != want:
            print("STALE: %s disagrees with %s" % (args.out, args.ledger))
            print("  regenerate with: python scripts/emit_paper_numbers.py")
            return 1
        print("OK: %s matches the ledger" % args.out)
        return 0

    parent = os.path.dirname(args.out)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(want)
    print("wrote %s" % args.out)
    for name, val in macros(measured(cells)):
        print("  \\%-18s %s" % (name, val))
    return 0


if __name__ == "__main__":
    sys.exit(main())
