#!/usr/bin/env python3
"""
emit_paper_numbers.py
Derive the manuscript's campaign numbers from the ledger instead of typing them.

The run count for the external campaign appeared in the manuscript in nine places and the discard
total in two. When the campaign grew, all eleven went stale together: the paper said `$80$ runs`
and `roughly $420{,}000$ discarded` when the ledger held `108` and `4{,}377{,}904`. Being wrong by
a factor of ten in a section whose entire argument is that benchmarks misreport their own sample
counts is not a typo, it is the paper committing the error it documents.

Hand-editing eleven sites is what created the problem, so this does not do that. It writes LaTeX
macros, the manuscript uses the macros, and the number exists once. `--check` verifies the
committed file still agrees with the ledger without rewriting it, so a build can gate on it.

The quantities are computed by `check_paper_omb_numbers.measured`, imported rather than
reimplemented -- two copies of this arithmetic would drift, and the drift would be invisible
because both would look authoritative.

CLI:
    python scripts/emit_paper_numbers.py
    python scripts/emit_paper_numbers.py --check
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from check_paper_omb_numbers import load_cells, measured  # noqa: E402
import audit_ledger  # noqa: E402
import check_fork_exposure  # noqa: E402
import priority_pairs  # noqa: E402
import recount_spans  # noqa: E402

DEFAULT_OUT = os.path.join("docs", "generated", "paper_numbers.tex")
DEFAULT_TABLE = os.path.join("docs", "generated", "grid_table.tex")
DEFAULT_REGISTRY_TABLE = os.path.join("docs", "generated", "registry_table.tex")
DEFAULT_PRIORITY_TABLE = os.path.join("docs", "generated", "priority_table.tex")
SPAN_CSV = os.path.join("docs", "results", "span_recount.csv")

HEADER = (
    "% Generated by scripts/emit_paper_numbers.py from the campaign ledger.\n"
    "% Do not edit by hand -- run the script and commit the result.\n"
    "% Every number below is recomputed from docs/results/external_campaigns_index.csv.\n"
)


def latex_thousands(n):
    """12345678 -> 12{,}345{,}678, the separator that survives LaTeX's math mode."""
    return "{,}".join(_chunks(str(int(n))))


def _chunks(s):
    """Digit groups of three, counted from the right."""
    head = len(s) % 3 or 3
    return [s[:head]] + [s[i:i + 3] for i in range(head, len(s), 3)]


def macros(m):
    """The (name, value) pairs the manuscript may reference.

    Names are deliberately verbose. A macro called `\\n` in a 3000-line manuscript is a trap, and
    a macro whose name does not say which campaign it counts is the same trap one level up.

    The Kafka/Redis split exists because the negative-sample story is scoped: the withdrawal
    rests on the Kafka-driver corpus staying at zero negatives, while the Redis-driver
    replication caught real ones. One unsplit total let a claim about one corpus be silently
    contradicted by the other.
    """
    out = [
        ("ombRuns", str(m["n_runs"])),
        ("ombDiscarded", latex_thousands(m["discarded_total"])),
        ("ombKept", latex_thousands(m["kept_total"])),
        ("ombNegatives", latex_thousands(m["negatives"])),
        ("ombKafkaDiscarded", latex_thousands(m["kafka_discarded"])),
        ("ombKafkaNegatives", latex_thousands(m["kafka_negatives"])),
        ("ombRedisDiscarded", latex_thousands(m["redis_discarded"])),
        ("ombRedisNegatives", latex_thousands(m["redis_negatives"])),
    ]
    if m["retention_min"] is not None:
        out.append(("ombRetentionMin", "%.2f" % m["retention_min"]))
        out.append(("ombRetentionMinExact", "%.4f" % m["retention_min"]))
    if m["retention_max"] is not None:
        out.append(("ombRetentionMax", "%.2f" % m["retention_max"]))
    return out


def span_macros(path=SPAN_CSV):
    """Negatives per span, from the committed recount.

    These exist because the manuscript spent two versions calling one span's negatives a
    causality violation. The correction is not a rewording: the acknowledgement-referenced
    span and the send-referenced span disagree, and only the first goes negative. A claim
    that specific has to be recomputed from the artefact every time the paper is built.

    Returns [] when the recount is absent, so a checkout without it still emits the campaign
    numbers; the manuscript's own tests are what forbid quoting a macro that does not exist.
    """
    if not os.path.exists(path):
        return []
    agg = recount_spans.totals(recount_spans.read_csv(path))
    out = [
        ("spanRuns", latex_thousands(agg["runs"])),
        ("spanEvents", latex_thousands(agg["events"])),
        ("spanNegAck", latex_thousands(agg["neg_ack"])),
        ("spanNegAckPct", "%.2f" % agg["pct_ack"]),
        ("spanNegSend", latex_thousands(agg["neg_send"])),
        ("spanNegOutputSend", latex_thousands(agg["neg_output_send"])),
        ("spanNegTti", latex_thousands(agg["neg_tti"])),
        ("spanRunsOverOnePct", latex_thousands(agg["runs_over_one_pct_ack"])),
        ("spanRunsAckOnly", latex_thousands(agg["runs_ack_only_inversions"])),
        # Conditioned on the runs that invert at all. Dividing by the whole corpus instead
        # buries the result: the runs where nothing inverted carry no information either way,
        # and including them turned 100% into 77%.
        ("spanRunsAckInverts", latex_thousands(agg["runs_ack_inverts"])),
        ("spanRunsAckOnlyPct", "%.0f" % (
            100.0 * agg["runs_ack_only_inversions"] / agg["runs_ack_inverts"]
            if agg["runs_ack_inverts"] else 0.0)),
        ("spanRunsSendInverts", latex_thousands(agg["runs_send_inverts"])),
        # The margin that does the actual excluding.
        ("spanDeepestInversionMs", "%.1f" % (agg["deepest_ack_inversion_us"] / 1000.0)),
        ("spanSendFloorUs", "%.0f" % agg["send_span_floor_us"]),
        ("spanOffsetMargin", "%.0f" % agg["offset_margin_factor"]),
    ]
    # Per-backend, because pooling hides the only control that separates "a property of
    # Kafka's client" from "a property of an acknowledgement-referenced span". Both backends
    # stamp on one host and one clock, so the broker is the sole variable across the columns.
    #
    # Only what the manuscript quotes is emitted. A generated file carrying macros nobody
    # reads is a place for a stale number to survive a revision, and the split already has
    # more counters than the text needs.
    rows = recount_spans.read_csv(path)
    split = recount_spans.by_backend(rows)
    floors = []
    for backend, agg in split.items():
        key = backend[:1].upper() + backend[1:]
        if not key.isalpha():  # macro names are LaTeX control words
            continue
        floors.append(agg["send_span_floor_us"])
        out.extend([
            ("span%sEvents" % key, latex_thousands(agg["events"])),
            ("span%sNegAck" % key, latex_thousands(agg["neg_ack"])),
            ("span%sNegAckPct" % key, "%.2f" % agg["pct_ack"]),
            ("span%sRunsAckInvertsPct" % key, "%.0f" % (
                100.0 * agg["runs_ack_inverts"] / agg["runs"] if agg["runs"] else 0.0)),
        ])
    # The pooled floor is the smaller of the two; the manuscript says so, so the other one
    # has to be a number it can print rather than a claim it makes.
    if len(floors) > 1:
        out.append(("spanSendFloorOtherUs", "%.0f" % max(floors)))
    return out


def traced_ratio_macros():
    """Traced-prediction over observed inversion, one ratio per arm that has both.

    These three numbers were typed into Section V-C. They are the paper's only unfitted
    cross-instrument check, and Section V-E now leans on them a second time: a kernel-only
    estimator that bracketed unity bounds any additional userspace delay between the wakeup
    and the clock read. A quantity carrying that much argument should not be hand-copied.

    The real-time arms floor at zero inversions, so they have no finite ratio and are
    skipped rather than reported as infinite.
    """
    import csv
    import glob
    ratios = []
    for path in sorted(glob.glob(os.path.join("docs", "results", "**", "runq_tail.csv"),
                                 recursive=True)):
        with open(path, encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                try:
                    inv = float(row["inversion"])
                    tail = float(row["p_tail"])
                except (KeyError, TypeError, ValueError):
                    continue
                if inv > 0:
                    ratios.append(tail / inv)
    if not ratios:
        return []
    ratios.sort()
    return [
        ("tracedRatios", ", ".join("%.2f" % r for r in ratios)),
        ("tracedRatioLo", "%.2f" % ratios[0]),
        ("tracedRatioHi", "%.2f" % ratios[-1]),
        ("tracedRatioArms", str(len(ratios))),
    ]


def stat_macros():
    """Interval estimates for the manipulation cells and the payload fit.

    The manuscript claims "disjoint Wilson intervals" and an effective exponent from four
    points. Both are checkable numbers, so both are emitted here rather than typed: a
    re-run that moves a cell moves the macro, and `--check` fails the build instead of
    letting the text and the artefact drift apart.

    Returns [] if the artefacts are absent, for the same reason span_macros() does.
    """
    try:
        import stat_intervals
    except ImportError:  # pragma: no cover - stat_intervals ships beside this file
        return []
    out = []
    try:
        cells = {lvl: (kb, nb, kr, nr) for lvl, kb, nb, kr, nr
                 in stat_intervals.priority_cells()}
    except (OSError, KeyError, ValueError):
        return []
    for level, name in (("l75", "Low"), ("l88", "High")):
        if level not in cells:
            continue
        kb, nb, kr, nr = cells[level]
        blo, bhi = stat_intervals.wilson(kb, nb)
        rlo, rhi = stat_intervals.wilson(kr, nr)
        z, ratio = stat_intervals.ratio_z(kb, nb, kr, nr)
        out += [
            ("rt%sBase" % name, "%.4f" % (kb / nb)),
            ("rt%sBaseCI" % name, "%.4f$--$%.4f" % (blo, bhi)),
            ("rt%sRt" % name, "%.4f" % (kr / nr)),
            ("rt%sRtCI" % name, "%.4f$--$%.4f" % (rlo, rhi)),
            ("rt%sFactor" % name, "%.0f" % round(ratio)),
            ("rt%sZ" % name, "%.1f" % z),
        ]
    # The geometry half of Table III was typed by hand while the priority half above came
    # from this function. Both halves make the same kind of claim from the same kind of
    # artefact, so both belong here: four rates, four intervals, two factors and two z's that
    # a re-run can move. Found while adding the figure that plots these same cells.
    for phase, name in (("ea6", "GeomOrig"), ("ea6b", "GeomRepl")):
        try:
            cells = stat_intervals.geometry_cells(phase)
        except (OSError, KeyError, ValueError):
            continue
        if len(cells) != 2:
            continue
        (_, kc, nc), (_, ks, ns) = cells
        clo, chi = stat_intervals.wilson(kc, nc)
        slo, shi = stat_intervals.wilson(ks, ns)
        z, ratio = stat_intervals.ratio_z(ks, ns, kc, nc)
        out += [
            ("%sConc" % name, "%.4f" % (kc / nc)),
            ("%sConcCI" % name, "%.4f$--$%.4f" % (clo, chi)),
            ("%sSpread" % name, "%.4f" % (ks / ns)),
            ("%sSpreadCI" % name, "%.4f$--$%.4f" % (slo, shi)),
            ("%sFactor" % name, "%.2f" % ratio),
            ("%sZ" % name, "%.1f" % abs(z)),
        ]
    try:
        slope, _, r2, lo, hi = stat_intervals.payload_fit()
        out += [
            ("tailExponent", "%.3f" % (-slope)),
            ("tailExponentCI", "%.3f$--$%.3f" % (-hi, -lo)),
            # Signed, for every place that says the word "slope". The magnitude above is for
            # the supplement's `T^{-\tailExponent}`, where the sign lives in the notation;
            # printing it beside a figure that draws the signed fit is how the paper came to
            # show 0.339 and -0.34 for one number on facing pages.
            ("tailSlope", "%.2f" % slope),
            # Self-mathed like every other CI here: the value is used inside $...$, closes
            # math around the word and reopens it, so the signs print as minus and
            # "to" prints roman. A bare hyphen in text mode would be neither.
            ("tailSlopeCI", "%.2f$ to $%.2f" % (lo, hi)),
            ("tailRsq", "%.3f" % r2),
        ]
    except (OSError, KeyError, ValueError):
        pass
    return out


def priority_residual_macros():
    """What the manipulated arm actually did across the whole ladder, not just the two tabled.

    Section V-C names a constant the model fixes in advance and the two pairs in Table II land
    on it. Over all eight pairs the real-time arm runs from well below that constant to well
    above it, and S47 was stating that range from two hand-typed numbers.
    """
    try:
        import priority_pairs
        pairs = priority_pairs.usable()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    if not pairs:
        return []
    rates = [p["rate_rt"] for p in pairs]
    return [
        ("rtResidualMin", "%.4f" % min(rates)),
        ("rtResidualMax", "%.4f" % max(rates)),
        ("rtResidualPairs", str(len(rates))),
    ]


def grid_macros():
    """Counts describing the grid-membership inference, after the Holm correction.

    The manuscript said "nine of ten powered arms reject" and named the wrong two arms as
    the exceptions: the two it named have no power at all, while the arm that actually
    fails the correction (900/s, raw 0.044, adjusted 0.131) was printed as a rejection.
    The count and the exception are therefore both derived here.
    """
    try:
        import stat_intervals
        cells = stat_intervals.grid_cells()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    powered = [c for c in cells if c["powered"]]
    reject = [c for c in powered if c["verdict"] == "grid"]
    unresolved = [c for c in powered if c["verdict"] == "not resolved"]
    out = [
        ("gridArms", str(len(cells))),
        ("gridPowered", str(len(powered))),
        ("gridReject", str(len(reject))),
        ("gridFlat", str(sum(1 for c in cells if not c["powered"]))),
    ]
    if unresolved:
        u = unresolved[0]
        out += [
            ("gridUnresolvedRate", str(u["rate_hz"])),
            ("gridUnresolvedRaw", "%.3f" % u["p_raw"]),
            ("gridUnresolvedHolm", "%.3f" % u["p_holm"]),
        ]
    flat = [c for c in cells if not c["powered"]]
    if len(flat) == 2:
        out.append(("gridFlatRates", "$%d$ and $%d$" % tuple(sorted(c["rate_hz"] for c in flat))))
    return out


def _fmt_p(value):
    return "$<0.001$" if value < 0.001 else "$%.3f$" % value


def render_grid_table():
    """Table II, generated from the artefact.

    The table was transcribed once and drifted from the correction its own caption
    claimed. A generated table cannot: the p-values it prints are the adjusted ones the
    caption promises, and the verdict column is a function of them.
    """
    import stat_intervals
    cells = stat_intervals.grid_cells()
    lines = [
        "% Generated by scripts/emit_paper_numbers.py from",
        "% docs/results/external/grid_membership.csv. Do not edit by hand.",
        "\\begin{tabular}{@{}rlrrrrl@{}}",
        "\\toprule",
        "rate & $p/q$ & $n$ & $D$ & null & $p_{\\mathrm{Holm}}$ & verdict \\\\",
        "\\midrule",
    ]
    for c in cells:
        lines.append("$%d$/s & $%d/%d$ & $%d$ & $%.3f$ & $%.3f$ & %s & %s \\\\"
                     % (c["rate_hz"], c["p"], c["q"], c["n"], c["d_observed"],
                        c["d_null"], _fmt_p(c["p_holm"]), c["verdict"]))
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def render_registry_table():
    """The audited-harness table, generated from the registry rather than transcribed.

    This one was written by hand, and it drifted inside a single revision: the main text
    gained the guard's scope -- the filter is on the end-to-end path, the publish path uses a
    nanosecond clock and no filter -- while the supplement's table went on showing one row
    per tool with no path column at all, which is the unscoped reading the main text had just
    corrected. A reader following the pointer to "the registry, in full" was handed the
    version the paper no longer stood behind.

    The grid table earned its place in this file the same way. A table that restates a
    computation belongs to the computation.
    """
    try:
        import harness_registry
        from audit_external_harness import DISPOSAL_KINDS
        folded = harness_registry.paths()
    except (ImportError, OSError, KeyError, ValueError):
        return ""
    # Round 7 found wrk2's Disposal cell rendering as "---", identical to the two
    # counterexamples: round 6 taught the classifier a class this map had never heard of, and
    # a tool the text convicts came out of the table acquitted. The assertion makes the next
    # such divergence a build failure instead of a referee finding, and the maps are module
    # constants now so the test suite can check them without rendering anything.
    missing = set(DISPOSAL_KINDS) - set(REGISTRY_LABELS)
    assert not missing, "disposal class(es) with no table label: %s" % sorted(missing)
    unciteable = {h for h, _ in folded} - set(REGISTRY_CITES)
    assert not unciteable, "harness(es) with no citation key: %s" % sorted(unciteable)
    lines = [
        "% Generated by scripts/emit_paper_numbers.py from",
        "% docs/results/external/harness_registry.csv. Do not edit by hand.",
        "\\begin{tabular}{@{}llllc@{}}",
        "\\toprule",
        "Tool & Span measured & Clock & Disposal & Counts \\\\",
        "\\midrule",
    ]
    source_keys = []
    for (harness, path), v in sorted(folded.items()):
        kinds = sorted(v["kinds"] & set(REGISTRY_LABELS))
        disposal = ", ".join(REGISTRY_LABELS[k] for k in kinds) if kinds else "---"
        lines.append("%s & %s & %s & %s & %s \\\\" % (
            _tt(harness), path, v["clock"], disposal,
            "yes" if v["counts_discards"] else "no"))
        source_keys.append(REGISTRY_CITES[harness])
    lines += ["\\bottomrule", "\\end{tabular}"]
    _ = source_keys  # the caption's source list is emitted by registry_sources_macro()
    return "\n".join(lines) + "\n"


def registry_sources_macro():
    """The caption's "Sources, in row order" list, generated from the same sorted fold
    that orders the table's rows.

    It was hand-written, and round 7 found it six keys long in the previous row order,
    directly beside the sentence "this table is generated at build time". The macro
    lives in paper_numbers.tex because the caption uses it before the tabular is input.
    """
    try:
        import harness_registry
        folded = harness_registry.paths()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    keys = [REGISTRY_CITES[h] for (h, _p), _v in sorted(folded.items())]
    return [("registryTableSources", "\\cite{%s}" % ",".join(keys))]


#: Disposal class -> table cell. Every class `classify()` can emit must appear here; the
#: renderer asserts it, and test_emit_paper_numbers pins it.
REGISTRY_LABELS = {
    "positive_only_filter": "filter",
    "silent_suppression": "substitute a constant",
    "library_refusal": "refused by own library",
}

#: Harness -> bibliography key for the caption's source list, in the rows' own order.
REGISTRY_CITES = {
    "OpenMessaging Benchmark": "openmessaging2018",
    "emqtt-bench": "emqtt_bench",
    "fio": "fio_gettime",
    "blktrace btt": "btt_inlines",
    "Rezolus": "rezolus",
    "Apache Pulsar perf": "pulsar_perf",
    "wrk2": "wrk2_src",
}


def _tt(name):
    """Tool names that are literal command names are set in a monospace face."""
    literal = {"emqtt-bench", "fio"}
    if name in literal:
        return "\\texttt{%s}" % name.replace("_", "\\_")
    if name == "blktrace btt":
        return "\\texttt{blktrace/btt}"
    if name == "OpenMessaging Benchmark":
        return "OpenMessaging Bench."
    return name


def retention_macros():
    """The cells behind the deletion claim, and the denominator the manuscript lacked.

    "The 49 runs on an unsaturated path" matched no partition of the artefact. What the
    artefact supports is the set of cells whose reported median lands on the millisecond
    grid, which is both checkable and the sharper claim.
    """
    try:
        import stat_intervals
        cells = stat_intervals.retention_cells()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    grid = [c for c in cells if c["p50_ms"] in (1.0, 2.0)]
    if not grid:
        return []
    lo = min(grid, key=lambda c: c["retention_pct"])
    hi = max(grid, key=lambda c: c["retention_pct"])
    pub = [c["pub_p50_ms"] for c in grid]
    rho = stat_intervals.spearman(pub, [c["retention_pct"] for c in grid])
    return [
        ("ombMedianCells", str(len(cells))),
        ("ombGridMedianCells", str(len(grid))),
        ("ombGridRetentionMin", "%.2f" % lo["retention_pct"]),
        ("ombGridRetentionMax", "%.0f" % hi["retention_pct"]),
        ("ombRetentionFold", "%.0f" % (hi["retention_pct"] / lo["retention_pct"])),
        ("ombKeptLo", latex_thousands(lo["kept"])),
        ("ombKeptHi", latex_thousands(hi["kept"])),
        ("ombPubLatLo", "%.1f" % min(pub)),
        ("ombPubLatHi", "%.1f" % max(pub)),
        ("ombRetentionRho", "%+.2f" % rho),
        ("ombRetentionRhoN", str(len(grid))),
    ]


def traced_macros():
    """The traced stall tail, estimated with intervals rather than eyeballed.

    The manuscript quoted a "windowed log-log index" off the same histogram and called it
    indistinguishable from the payload-sweep exponent. It is not an independent
    confirmation: a least-squares slope through four nested survival points returns a
    number whether or not the points lie on a line, and here the per-octave indices differ
    by two orders of magnitude, so no single index describes the window. Both the
    model-free estimate and the evidence against the power law are emitted.
    """
    try:
        import tail_index_traced
        rows = [r for r in tail_index_traced.report() if r.get("tag") == "ea9/l88_base"]
    except (ImportError, OSError, ValueError):
        return []
    if not rows:
        return []
    r = rows[0]
    out = [
        ("tracedEvents", latex_thousands(r["traced_events"])),
        ("tracedMleAlpha", "%.2f" % r["mle_alpha"]),
        ("tracedMleCI", "%.2f$--$%.2f" % (r["mle_lo"], r["mle_hi"])),
    ]
    if "exc_alpha" in r:
        out += [
            ("tracedExcAlpha", "%.2f" % r["exc_alpha"]),
            ("tracedExcCI", "%.2f$--$%.2f" % (r["exc_lo"], r["exc_hi"])),
        ]
    if len(r["octaves"]) >= 2:
        out += [
            ("tracedOctaveA", "%.2f" % r["octaves"][0][1]),
            ("tracedOctaveB", "%.2f" % r["octaves"][1][1]),
        ]
    top = [m for m in r.get("modes", []) if m[0] >= 1024]
    if top:
        lo, _, share, ratio = max(top, key=lambda m: m[1])
        out += [
            ("tracedModeLo", "%.0f" % (lo / 1024.0)),
            ("tracedModeHi", "%.0f" % (2 * lo / 1024.0)),
            ("tracedModeShare", "%.1f" % (100 * share)),
            ("tracedModeRatio", "%.1f" % ratio),
            ("tracedModes", str(len(r.get("modes", [])))),
        ]
    if "tail_alpha" in r:
        out += [
            ("tracedTailAlpha", "%.2f" % r["tail_alpha"]),
            ("tracedTailCI", "%.2f$--$%.2f" % (r["tail_lo"], r["tail_hi"])),
            ("tracedTailFrom", "%.0f" % (r["tail_from_us"] / 1024.0)),
        ]
    if "gof_p" in r and r["gof_boot"]:
        out += [
            ("tracedGofP", ("<%.4f" % (1.0 / r["gof_boot"])) if r["gof_p"] == 0
             else "%.3f" % r["gof_p"]),
            ("tracedGofBoot", latex_thousands(r["gof_boot"])),
        ]
    return out


def tost_macros(path=os.path.join("docs", "results", "transport_rt",
                                  "transport_realtime_gated_tost.csv")):
    """The equivalence result the manuscript asserted without printing.

    The text claimed "the equivalence claim is a TOST at a 1 ms margin" and then gave no
    test result, which is the same omission the paper criticises elsewhere.
    """
    if not os.path.exists(path):
        return []
    import csv
    with open(path, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        return []
    shifts = [float(r["hl_shift"]) for r in rows]
    first = rows[0]
    return [
        ("tostMargin", "%.0f" % float(first["margin"])),
        ("tostHL", "%.3f" % float(first["hl_shift"])),
        ("tostHLCI", "%.3f$--$%.3f" % (float(first["hl_ci90_lo"]),
                                       float(first["hl_ci90_hi"]))),
        ("tostHLRange", "%.3f$--$%.3f" % (min(shifts), max(shifts))),
        ("tostLevels", str(len(rows))),
    ]


def mechanism_macros():
    """Quantities the manuscript stated in words that the artefacts state as numbers.

    Each of these was quoted wrongly at least once: the harness totals as a round "1.5
    million" that matches neither topology; the inversion ceiling as a claim about how many
    threads are unpreempted; the idle-to-knee growth as "mass beyond one millisecond" when
    the artefact holds an inversion rate; and the tracer's own effect not at all.
    """
    try:
        import stat_intervals
    except ImportError:  # pragma: no cover - ships beside this file
        return []
    out = []
    try:
        h = stat_intervals.harness_cells()
        for key, name in (("one_clock", "OneClock"), ("cross_host", "CrossHost")):
            if key in h:
                out += [("harness%sSamples" % name, latex_thousands(h[key]["sent"])),
                        ("harness%sNegatives" % name, latex_thousands(h[key]["negatives"])),
                        ("harness%sRuns" % name, str(h[key]["runs"]))]
    except (OSError, KeyError, ValueError):
        pass
    try:
        b = stat_intervals.occupancy_bounds()
        if "ceiling" in b:
            out.append(("invCeiling", "%.2f" % b["ceiling"]))
    except (OSError, KeyError, ValueError):
        pass
    try:
        g = stat_intervals.load_growth()
        if g:
            out += [("coreGrowth", "%.0f" % g["core_growth"]),
                    ("invGrowth", "%.0f" % g["inv_growth"])]
    except (OSError, KeyError, ValueError):
        pass
    try:
        o = stat_intervals.observer_effect()
        if o:
            out += [("untracedRate", "%.3f" % o["untraced"]),
                    ("tracedRate", "%.3f" % o["traced"]),
                    ("observerZ", "%.1f" % o["z"])]
    except (OSError, KeyError, ValueError):
        pass
    return out


def kernel_macros():
    """The scheduler constants Section V-G explains the traced mode with.

    Derived, not measured: the campaign never captured them and the machines are gone after
    the tenancy lapses. Every input is public -- the published kernel config (committed with
    its SHA256), the CPU count recovered from the campaign's own k/rho, and the formula in
    v6.8 fair.c -- so a reader can repeat the whole chain. See scripts/kernel_constants.py.
    """
    try:
        import kernel_constants
        c = kernel_constants.constants()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    return [
        ("kernelHz", str(c["config_hz"])),
        ("tickMs", "%.0f" % c["tick_ms"]),
        ("testbedCpus", str(c["cpus"])),
        ("sliceFactor", str(c["sysctl_factor"])),
        ("baseSliceMs", "%.0f" % c["base_slice_ms"]),
        ("baseSliceNs", latex_thousands(c["base_slice_ns"])),
        ("cpuEstimateSpread", "%.2f" % c["cpu_spread"]),
    ]


_SPELLED = ("zero", "one", "two", "three", "four", "five", "six",
            "seven", "eight", "nine", "ten", "eleven", "twelve")


def _spell(n):
    """A small count as a word, for prose. Above twelve, IEEE style takes the digits back."""
    return _SPELLED[n] if 0 <= n < len(_SPELLED) else str(n)


def registry_macros():
    """The audited-harness survey in Section II, counted rather than asserted.

    Every one of these is a fold over docs/results/external/harness_registry.csv whose class
    labels are recomputed from the committed evidence lines by the same classifier that read
    our own corpus. If a later edit loosens a pattern, these numbers move, the ledger check
    fails, and the sentence in Section II cannot be built until someone looks.
    """
    try:
        import harness_registry
        from audit_external_harness import DISPOSAL_KINDS
        s = harness_registry.summary()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    out = [
        ("harnessAudited", str(s["harnesses"])),
        ("harnessVendors", str(s["vendors"])),
        ("harnessLanguages", str(s["languages"])),
        ("harnessEvidenceLines", str(s["evidence_lines"])),
        ("harnessSilent", str(s["n_silent"])),
        # Silent harnesses other than the audited subject itself: the count the text
        # uses for "independent tools", which round 6 caught as prose that only
        # happened to be right after the re-audit.
        ("harnessSilentIndependent",
         str(len([h for h in s["silent"] if h != "OpenMessaging Benchmark"]))),
        ("harnessFilters", str(len(s["filters"]))),
        ("harnessSuppressors", str(len(s["suppressors"]))),
        ("harnessCounting", str(len(s["counts_discards"]))),
        ("harnessRefusals", str(len(s["library_refusals"]))),
        # How many disposal classes there are, which the paragraph in IV-D was asserting from
        # prose and asserting wrongly: it said four while the taxonomy has three and the
        # sentence itself enumerated three. The size of DISPOSAL_KINDS is not a fact about
        # this campaign, it is a fact about the classifier, and it is countable.
        ("harnessDisposalClasses", str(len(DISPOSAL_KINDS))),
        # The tool in no disposal class at all. emqtt-bench guards a counter rather than the
        # sample, so it neither discards nor counts a discard, and lumping it with the tool
        # that counts is what left Section IV-D describing it as "a fifth entry" of nothing.
        ("harnessNoDisposal",
         str(s["harnesses"] - s["n_silent"] - len(s["counts_discards"]))),
    ]
    # Spelled forms of the same counts. IEEE house style wants a small number spelled in
    # prose; the alternative to emitting the word was transcribing it, which is the failure
    # mode this whole file exists to prevent.
    spelled = [(name, _spell(int(value))) for name, value in list(out)
               if name.startswith("harness") and value.isdigit() and int(value) <= 12]
    out += [(name + "Word", word) for name, word in spelled]
    # And the same word capitalised, because several of these open a sentence and a macro
    # cannot know that it does. Emitting both beats teaching the manuscript to remember.
    out += [(name + "WordCap", word[:1].upper() + word[1:]) for name, word in spelled]
    # The scope of the guard, computed rather than remembered. A referee who opens
    # MessageProducer.java finds a nanosecond clock and no filter, and will read an
    # unqualified "the benchmark filters" as overstated. These macros make the qualifier a
    # property of the evidence: which span is guarded, and which clock each span uses.
    try:
        contrast = harness_registry.within_harness_contrast()
    except (OSError, KeyError, ValueError):
        return out
    omb = contrast.get("OpenMessaging Benchmark")
    if omb:
        (gpath, gclock) = omb["guarded"][0]
        (upath, uclock) = omb["unguarded"][0]
        out += [
            ("ombGuardedPath", gpath),
            ("ombGuardedClock", gclock),
            ("ombUnguardedPath", upath),
            ("ombUnguardedClock", uclock),
        ]
    out.append(("harnessSplitGuard", str(len(contrast))))
    return out


def clocksource_macros():
    """The clocksource bound, derived from the probe's own measurement.

    A reviewer asked which clocksource the instances ran and we could not say: the field was
    never captured and the machines are gone. The probe did capture the smallest increment
    the clock could report, and read cost separates the candidates by an order of magnitude,
    so the set is recoverable even though the value is not. See scripts/clocksource_bound.py.
    """
    try:
        import clocksource_bound
        b = clocksource_bound.bound()
    except (ImportError, OSError, KeyError, ValueError):
        return []
    return [
        ("clockIncrementNs", "%.0f" % b["increment_ns"]),
        ("clockPmTickNs", "%.0f" % b["pm_timer_tick_ns"]),
        ("clockAdmitted", " or ".join("\\texttt{%s}" % n for n in b["admitted"])),
        ("clockExcludedCount", str(len(b["excluded"]))),
    ]


def audit_macros():
    """The consistency audit, from the two per-condition integrity files.

    These were literals in both documents for sixteen rounds -- the only headline outside the
    ledger, and the one in the contribution about publishing the record behind a number. They
    reproduce exactly from the audit's own outputs; what was missing was the derivation, so a
    reader had to know which of several CSVs to open. Now they are emitted like everything
    else.
    """
    a = audit_ledger.audit()
    total, work, cloud = a["total"], a["workstation"], a["cloud"]
    out = []
    for prefix, c in (("", total), ("Workstation", work), ("Cloud", cloud)):
        out.extend([
            ("auditRuns" + prefix, latex_thousands(c["runs"])),
            ("auditRejected" + prefix, latex_thousands(c["rejected"])),
            ("auditPct" + prefix, "%.1f" % c["pct"]),
            ("auditConditions" + prefix, latex_thousands(c["conditions"])),
            ("auditUsableConditions" + prefix, latex_thousands(c["usable_conditions"])),
        ])
    return out


def priority_macros():
    """The real-time-priority collapse, over every matched pair that ran.

    The manuscript quotes a range across eight pairs and showed two of them. The range was
    right and reproduced from the artifacts; nothing led a reader to it, and the pair at its
    lower bound -- the weakest result in the series -- appeared nowhere. It is derived now.

    `rtLowFactor` and `rtHighFactor` are left alone: they are the two pairs Table II reports,
    a different and correctly narrower claim, and the supplement says which is which.
    """
    s = priority_pairs.summary()
    return [
        ("rtPairs", str(s["pairs"])),
        ("rtFactorLow", "%.0f" % s["factor_low"]),
        ("rtFactorHigh", "%.0f" % s["factor_high"]),
        ("rtRhoLow", str(s["level_low"])),
        ("rtRhoHigh", str(s["level_high"])),
        ("rtConfounded", str(s["confounded"])),
    ]


def render_priority_table():
    """Every matched pair, one row each, generated from the three campaign files.

    Transcription is what produced a two-row table that outlived the campaign by six pairs.
    """
    rows = priority_pairs.usable()
    lines = [
        "% Generated by scripts/emit_paper_numbers.py from",
        "% docs/results/model/stamping_priority*.csv. Do not edit by hand.",
        "\\begin{tabular}{@{}llrrrr@{}}",
        "\\toprule",
        "campaign & load & $\\rho$ & ordinary & real-time & factor \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append("%s & $%s\\%%$ & $%.4f$ & $%.4f$ & $%.4f$ & $%.0f\\times$ \\\\"
                     % (r["campaign"], r["level"].lstrip("l"), r["rho"],
                        r["rate_base"], r["rate_rt"], r["factor"]))
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)


def fork_macros():
    """How far the guard has travelled, from the committed survey.

    "More than a dozen public forks" was a claim no reader could check and a referee tried.
    `scripts/check_fork_exposure.py` walks the fork list and writes what it found; this reads
    that file, so the build needs no network and the number has a record behind it.
    """
    rows = check_fork_exposure.read_record()
    if not rows:
        return []
    t = check_fork_exposure.totals(rows)
    stamp = rows[0].get("checked_utc", "")
    return [
        ("forkChecked", str(t["checked"])),
        ("forkUnchanged", str(t["unchanged"])),
        ("forkAbsent", str(t["absent"])),
        ("forkCheckedOn", stamp),
    ]


def all_pairs(m):
    return (list(macros(m)) + span_macros() + stat_macros() + grid_macros()
            + retention_macros() + traced_macros() + tost_macros()
            + mechanism_macros() + kernel_macros() + registry_macros()
            + registry_sources_macro()
            + clocksource_macros() + traced_ratio_macros() + audit_macros()
            + priority_macros() + priority_residual_macros() + fork_macros())


def render(m):
    body = "".join("\\newcommand{\\%s}{%s}\n" % (name, val) for name, val in all_pairs(m))
    return HEADER + body


def main(argv=None):
    ap = argparse.ArgumentParser(description="Emit campaign numbers as LaTeX macros")
    ap.add_argument("--ledger", default=os.path.join("docs", "results",
                                                     "external_campaigns_index.csv"))
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--table", default=DEFAULT_TABLE)
    ap.add_argument("--registry-table", default=DEFAULT_REGISTRY_TABLE)
    ap.add_argument("--priority-table", default=DEFAULT_PRIORITY_TABLE)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file disagrees with the ledger; write nothing")
    args = ap.parse_args(argv)

    if not os.path.exists(args.ledger):
        print("missing: %s" % args.ledger)
        return 1
    cells = load_cells(args.ledger)
    if not cells:
        print("no admissible cells in %s -- refusing to emit numbers from nothing" % args.ledger)
        return 1

    m = measured(cells)
    # Both generated files are gated together. The grid table was the one place a number
    # reached the page without passing through this script, and it is the one place the
    # paper contradicted its own caption.
    targets = [(args.out, render(m))]
    try:
        targets.append((args.table, render_grid_table()))
    except (ImportError, OSError, KeyError, ValueError) as exc:
        print("note: grid table not generated (%s)" % exc)
    reg = render_registry_table()
    if reg:
        targets.append((args.registry_table, reg))
    try:
        targets.append((args.priority_table, render_priority_table()))
    except (ImportError, OSError, KeyError, ValueError) as exc:
        print("note: priority table not generated (%s)" % exc)

    if args.check:
        stale = False
        for path, want in targets:
            if not os.path.exists(path):
                print("missing: %s (run without --check to create it)" % path)
                stale = True
                continue
            with open(path, encoding="utf-8") as fh:
                have = fh.read()
            if have.replace("\r\n", "\n") != want:
                print("STALE: %s disagrees with the artefacts" % path)
                stale = True
        if stale:
            print("  regenerate with: python scripts/emit_paper_numbers.py")
            return 1
        print("OK: %s generated file(s) match the artefacts" % len(targets))
        return 0

    for path, want in targets:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(want)
        print("wrote %s" % path)
    for name, val in all_pairs(m):
        print("  \\%-22s %s" % (name, val))
    return 0


if __name__ == "__main__":  # pragma: no cover - dispatch only; main() is tested directly
    sys.exit(main())
