#!/usr/bin/env bash
# Shared configuration for every cloud campaign.
#
# The campaign scripts were originally generated ad hoc with host addresses substituted in,
# which meant the results in the manuscript could not be regenerated by anyone - including us.
# They are parameterised here so a fresh testbed only needs hosts.env.
#
# Usage:  cp cloud/hosts.env.example cloud/hosts.env   # then edit
#         bash cloud/campaigns/concurrency.sh
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$HOME/sbl}"
HOSTS_ENV="${HOSTS_ENV:-$(dirname "${BASH_SOURCE[0]}")/../hosts.env}"

if [ -f "$HOSTS_ENV" ]; then
  # shellcheck disable=SC1090
  . "$HOSTS_ENV"
fi

: "${BROKER_PRIV:?set BROKER_PRIV (private IP of the broker host) in cloud/hosts.env}"
: "${BROKER2_PRIV:=}"
: "${BROKER3_PRIV:=}"
: "${SSH_KEY:=$HOME/.ssh/oci_sbl}"

KAFKA_BOOTSTRAP="${KAFKA_BOOTSTRAP:-$BROKER_PRIV:19092}"
KAFKA_CLUSTER_BOOTSTRAP="${KAFKA_CLUSTER_BOOTSTRAP:-$BROKER_PRIV:29092}"
REDIS_HOST="${REDIS_HOST:-$BROKER_PRIV}"
REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_CLUSTER_PORT="${REDIS_CLUSTER_PORT:-7000}"

# The Kafka producer must be pipelined or its scheduling lag dominates TTI. This is
# measurement defect #3 in the manuscript; leaving it out silently reproduces the defect.
KAFKA_PRODUCER_EXTRA="${KAFKA_PRODUCER_EXTRA:---max-inflight 64}"

cd "$REPO_ROOT"
PLAN="$(find data -name replay_plan.csv | head -1)"
PLANS_DIR="$(dirname "$(dirname "$PLAN")")"
: "${PLAN:?no replay plans found under data/ - run scripts/fetch_statsbomb_corpus.py first}"

remote_broker () {  # run a command on the broker host
  ssh -i "$SSH_KEY" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
      "ubuntu@$BROKER_PRIV" "$@"
}

# Apply/clear injected one-way egress delay at the broker NIC.
netem () {
  remote_broker "~/netem.sh ${1:-0}" >/dev/null 2>&1 || true
}

banner () { echo "=== $* $(date +%H:%M:%S) ==="; }
